version: "1.0"

simulation:
  duration: 1000.0
  logging:
    level: "INFO"
    file: "simulation.log"

network:
  strategy: "uneven"
  links:
    - id: "link1"
      capacity: 10240
      time_window_duration: 60
      target_utilization: 0.2
    - id: "link2"
      capacity: 10240
      time_window_duration: 60
      target_utilization: 0.8
    - id: "link3"
      capacity: 10240
      time_window_duration: 60
      target_utilization: 0.8
    - id: "link4"
      capacity: 10240
      time_window_duration: 60
      target_utilization: 0.8 

traffic:
  flow_arrival:
    type: "poisson"
    rate: 10.0
  
  flow_size:
    type: "bounded_pareto"
    params:
      alpha: 1.2  # Adjusted for ML workload distribution
      lower: 512  # Minimum flow size for gradient updates
      upper: 1048576  # Large messages for model synchronization
